apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fence-deployment
spec:
  replicas: 2
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: fence
    spec:
      volumes:
        - name: config-volume
          secret:
            secretName: "fence-secret"
        - name: fence-jwt-keys
          secret:
            secretName: "fence-jwt-keys"
        - name: fence-yaml
          configMap:
            name: fence
      containers:
      - name: fence
        image: quay.io/cdis/fence:feat_jwt
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /_status
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 30
        ports:
        - containerPort: 80
        volumeMounts:
          - name: "config-volume"
            readOnly: true
            mountPath: "/var/www/fence/local_settings.py"
            subPath: local_settings.py
          - name: "fence-yaml"
            mountPath: "/var/www/fence/user.yaml"
            subPath: user.yaml
          - name: "fence-jwt-keys"
            readOnly: true
            mountPath: "/fence/keys"
      imagePullSecrets:
        - name: cdis-devservices-pull-secret
