apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: manifest-service-deployment
spec:
  selector:
    # Only select pods based on the 'app' label
    matchLabels:
      app: manifest_service
      release: production
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: manifest_service
        release: production
        GEN3_DATE_LABEL
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - manifest_service
              topologyKey: "kubernetes.io/hostname"
      automountServiceAccountToken: false
      volumes:
        - name: config-volume
          secret:
            secretName: "manifest-service-secret"
        - name: creds-volume
          secret:
            secretName: "manifestservice-g3auto"
        - name: config-helper
          configMap:
            name: config-helper
        - name: cert-volume
          secret:
            secretName: "cert-manifest-service-service"
        - name: ca-volume
          secret:
            secretName: "service-ca"
      terminationGracePeriodSeconds: 50
      containers:
        - name: manifest_service
          GEN3_MANIFEST_SERVICE_IMAGE
          livenessProbe:
            httpGet:
              path: /_status?timeout=20
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 30
          readinessProbe:
            httpGet:
              path: /_status?timeout=2
              port: 80
          ports:
          - containerPort: 80
          - containerPort: 443
          env:
          - name: DICTIONARY_URL
            valueFrom:
              configMapKeyRef:
                name: manifest-global
                key: dictionary_url
          - name: REQUESTS_CA_BUNDLE
            #
            # override python 'requests' SSL certificate bundle
            # to use system trusted certs
            # which includes our private certificate authority
            #
            value: /etc/ssl/certs/ca-certificates.crt
          - name: GEN3_DEBUG
            GEN3_DEBUG_FLAG|-value: "False"-|
          volumeMounts:
            - name: "config-volume"
              readOnly: true
              mountPath: "/var/www/manifest_service/wsgi.py"
              subPath: "wsgi.py"
            - name: "creds-volume"
              readOnly: true
              mountPath: "/var/www/manifest_service/creds.json"
              subPath: creds.json
            - name: "config-helper"
              readOnly: true
              mountPath: "/var/www/manifest_service/config_helper.py"
              subPath: config_helper.py  
            - name: "cert-volume"
              readOnly: true
              mountPath: "/mnt/ssl/service.crt"
              subPath: "service.crt"
            - name: "cert-volume"
              readOnly: true
              mountPath: "/mnt/ssl/service.key"
              subPath: "service.key"
            - name: "ca-volume"
              # See https://askubuntu.com/questions/645818/how-to-install-certificates-for-command-line
              readOnly: true
              mountPath: "/usr/local/share/ca-certificates/cdis/cdis-ca.crt"
              subPath: "ca.pem"
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 1
            limits:
              cpu: 2
              memory: 1024Mi
