apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: aws-iam-tester
  labels:
    app: aws-iam-tester
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0 
  selector:
    matchLabels:
      app: aws-iam-tester
  template:
    metadata:
      labels:
        app: aws-iam-tester
      annotations:
        iam.amazonaws.com/role: bucket_writer_tedtest1-databucket-gen3
    spec:
      nodeName: ip-172-24-68-184.ec2.internal
      tolerations:
       - key: kiam
         value: kiam
         effect: NoSchedule
       - key: role
         value: jupyter
         effect: NoSchedule
      containers:
      - name: aws-iam-tester
        image: mesosphere/aws-cli:latest
        imagePullPolicy: Always
        command:
          - /bin/sleep
        args:
          - "3600"
        env:
          - name: AWS_DEFAULT_REGION
            value: us-east-1
