apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pidgin-deployment
spec:
  selector:
    # Only select pods based on the 'app' label
    matchLabels:
      app: pidgin
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: pidgin
        GEN3_DATE_LABEL
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - pidgin
              topologyKey: "kubernetes.io/hostname"
      automountServiceAccountToken: false
      volumes:
        - name: shared-data
          emptyDir: {}
        - name: cert-volume
          secret:
            secretName: "cert-pidgin-service"
        - name: ca-volume
          secret:
            secretName: "service-ca"
      containers:
        - name: pidgin
          GEN3_PIDGIN_IMAGE
          env:
          - name: GEN3_DEBUG
            GEN3_DEBUG_FLAG|-value: "False"-|
          - name: GEN3_SIDECAR
            value: "GEN3_SHEEPDOG_SIDECAR|-False-|"            
          volumeMounts:
            - name: "shared-data"
              mountPath: "/var/run/gen3"
            - name: "cert-volume"
              readOnly: true
              mountPath: "/mnt/ssl/service.crt"
              subPath: "service.crt"
            - name: "cert-volume"
              readOnly: true
              mountPath: "/mnt/ssl/service.key"
              subPath: "service.key"
            - name: "ca-volume"
              readOnly: true
              mountPath: "/mnt/ssl/cdis-ca.crt"
              subPath: "ca.pem"
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 0.8
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /_status
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 30
          readinessProbe:
            httpGet:
              path: /_status
              port: 80
          ports:
          - containerPort: 80
          - containerPort: 443          
        #
        # Containers interact via /var/run/gen3/uwsgi.sock ...
        # Note: the sidecar is disabled unless GEN3_PEREGRINE_SIDECAR
        #   is enabled in the manifest
        #
        - name: sidecar
          GEN3_SIDECAR_IMAGE|-image: 'quay.io/cdis/sidecar:1.3.1-sidecar'-|
          ports:
          - containerPort: 80
          - containerPort: 443
          env:
          - name: GEN3_UWSGI_TIMEOUT
            value: "GEN3_PEREGRINE_SIDECAR_TIMEOUT|-45-|"
          - name: GEN3_SIDECAR
            value: "GEN3_PEREGRINE_SIDECAR|-False-|"
          volumeMounts:
            - name: "shared-data"
              mountPath: "/var/run/gen3"
            - name: "cert-volume"
              readOnly: true
              mountPath: "/mnt/ssl/service.crt"
              subPath: "service.crt"
            - name: "cert-volume"
              readOnly: true
              mountPath: "/mnt/ssl/service.key"
              subPath: "service.key"
            - name: "ca-volume"
              # See https://askubuntu.com/questions/645818/how-to-install-certificates-for-command-line
              readOnly: true
              mountPath: "/usr/local/share/ca-certificates/cdis-ca.crt"
              subPath: "ca.pem"
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 0.3
              memory: 256Mi
