kind: Service
apiVersion: v1
metadata:
  name: indexd-service
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: indexd_mapping
      prefix: /index/
      service: indexd-service
spec:
  selector:
    app: indexd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 
      name: http
    - protocol: TCP 
      port: 443 
      targetPort: 443
      name: https
  type: NodePort

